# Generated by Django 5.1.4 on 2024-12-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tumbnail_url',
            field=models.ImageField(max_length=200, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tumbnail_url',
            field=models.ImageField(max_length=200, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tumbnail_url',
            field=models.ImageField(max_length=200, upload_to='uploads/'),
        ),
    ]
