# Generated by Django 5.1.4 on 2024-12-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_learning', '0002_alter_course_tumbnail_url_alter_subject_tumbnail_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tumbnail_url',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='tumbnail_url',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tumbnail_url',
            new_name='thumbnail_url',
        ),
    ]
