# Generated by Django 5.1.4 on 2024-12-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_learning', '0005_exam_attempt_exam_result_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attempt',
            name='create_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_learning.create_exam'),
        ),
    ]
