# Generated by Django 5.1.4 on 2024-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_learning', '0006_exam_attempt_create_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attempt',
            name='option_a',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam_attempt',
            name='option_b',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam_attempt',
            name='option_c',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam_attempt',
            name='option_d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam_attempt',
            name='right_ans',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
