# Generated by Django 5.1.4 on 2024-12-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_learning', '0008_remove_exam_attempt_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_attempt',
            name='create_exam',
        ),
        migrations.AddField(
            model_name='exam_attempt',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_learning.exam'),
        ),
    ]
